Fix delete branch changes workflow
Debug

Try

Try

Fix

diff --git a/.github/workflows/branch-changes-delete.yaml b/.github/workflows/branch-changes-delete.yaml
--- a/.github/workflows/branch-changes-delete.yaml
+++ b/.github/workflows/branch-changes-delete.yaml
@@ -58,6 +58,7 @@ jobs:
           if replicated channel ls | grep -q ${{ steps.generate-channel-info.outputs.channel-name }}; then
             CHANNEL_DELETE_REQUIRED="true"
             CHANNEL_ID=$(replicated channel ls | grep ${{ steps.generate-channel-info.outputs.channel-name }} | awk '{print $1}')
+            echo "Detected channel ID: $CHANNEL_ID. Deleting channel..."
             echo "channel-id=${CHANNEL_ID}" >> "$GITHUB_OUTPUT"
           fi
 
@@ -71,16 +72,31 @@ jobs:
           REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
         run: |
           set -eu
+
           echo "::group::Updating customers to Stable channel"
-            CUSTOMERS=$(replicated customer ls | grep ${{ steps.generate-channel-info.outputs.channel-name }})
+
+          # Get the customers list and avoid script failure if no matches found
+          CUSTOMERS=$(replicated customer ls | grep "${{ steps.generate-channel-info.outputs.channel-name }}" || true)
+
+          # Check if CUSTOMERS is empty
+          if [ -z "$CUSTOMERS" ]; then
+            echo "No customers found for the specified channel."
+          else
+            echo "Updating the following customers:"
+            echo "$CUSTOMERS"
+
             while IFS= read -r customer; do
               CUSTOMER_ID=$(echo $customer | awk '{print $1}')
               CUSTOMER_NAME=$(echo $customer | awk '{print $2}')
+              echo "Updating customer $CUSTOMER_NAME to Stable channel"
               replicated customer update \
                 --channel "Stable" \
                 --name "${CUSTOMER_NAME}" \
                 --customer "${CUSTOMER_ID}"
+              echo "Customer $CUSTOMER_NAME updated to Stable channel"
             done <<< "$CUSTOMERS"
+          fi
+
           echo "::endgroup::"
 
       - name: Delete channel
